### SVM

## 1 Считываем данные

In [37]:
import pandas as pd

In [38]:
data=pd.read_csv('/home/abylaihan/Загрузки/lab2/data.csv')
data

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0,12/7/2009,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,Alloy,89046,OTHER ASIAN,MEDIUM,OTHER,8155.0,9829.0,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,2,0,12/7/2009,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,Alloy,93593,AMERICAN,LARGE TRUCK,CHRYSLER,6854.0,8383.0,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,3,0,12/7/2009,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,Covers,73807,AMERICAN,MEDIUM,CHRYSLER,3202.0,4760.0,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,4,0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,5,0,12/7/2009,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,Covers,69367,AMERICAN,COMPACT,FORD,3913.0,5054.0,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72978,73010,1,12/2/2009,ADESA,2001,8,MERCURY,SABLE,GS,4D SEDAN GS,BLACK,AUTO,1.0,Alloy,45234,AMERICAN,MEDIUM,FORD,1996.0,2993.0,2656.0,3732.0,2190.0,3055.0,4836.0,5937.0,NaN,NaN,18111,30212,GA,4200.0,0,993
72979,73011,0,12/2/2009,ADESA,2007,2,CHEVROLET,MALIBU 4C,LS,4D SEDAN LS,SILVER,AUTO,NaN,NaN,71759,AMERICAN,MEDIUM,GM,6418.0,7325.0,7431.0,8411.0,6785.0,8132.0,10151.0,11652.0,NaN,NaN,18881,30212,GA,6200.0,0,1038
72980,73012,0,12/2/2009,ADESA,2005,4,JEEP,GRAND CHEROKEE 2WD V,Lar,4D WAGON LAREDO,SILVER,AUTO,1.0,Alloy,88500,AMERICAN,MEDIUM SUV,CHRYSLER,8545.0,9959.0,9729.0,11256.0,8375.0,9802.0,11831.0,14402.0,NaN,NaN,18111,30212,GA,8200.0,0,1893
72981,73013,0,12/2/2009,ADESA,2006,3,CHEVROLET,IMPALA,LS,4D SEDAN LS,WHITE,AUTO,1.0,Alloy,79554,AMERICAN,LARGE,GM,6420.0,7604.0,7434.0,8712.0,6590.0,7684.0,10099.0,11228.0,NaN,NaN,18881,30212,GA,7000.0,0,1974
72982,73014,0,12/2/2009,ADESA,2006,3,MAZDA,MAZDA6,s,4D SEDAN S,SILVER,AUTO,1.0,Alloy,66855,OTHER ASIAN,MEDIUM,OTHER,7535.0,8771.0,8638.0,9973.0,7730.0,9102.0,11954.0,13246.0,NaN,NaN,18111,30212,GA,8000.0,0,1313

In [39]:
f = open('/home/abylaihan/Загрузки/lab2/Data_Dictionary.txt', 'r')
while True:
    line = f.readline()
    if line == '':
        break
    print(line)
f.close()

Field Name				Definition

RefID				        Unique (sequential) number assigned to vehicles

IsBadBuy				Identifies if the kicked vehicle was an avoidable purchase

PurchDate				The Date the vehicle was Purchased at Auction

Auction					Auction provider at which the  vehicle was purchased

VehYear					The manufacturer's year of the vehicle

VehicleAge				The Years elapsed since the manufacturer's year

Make					Vehicle Manufacturer

Model					Vehicle Model

Trim					Vehicle Trim Level

SubModel				Vehicle Submodel

Color					Vehicle Color

Transmission				Vehicles transmission type (Automatic, Manual)

WheelTypeID				The type id of the vehicle wheel

WheelType				The vehicle wheel type description (Alloy, Covers)

VehOdo					The vehicles odometer reading

Nationality				The Manufacturer's country

Size					The size category of the vehicle (Compact, SUV, etc.)

TopThreeAmericanName			Identifies if the manufacturer is one of the top three American manufacturers

MMRAcquisitionAuctionAveragePrice	Acquisition price for this vehicle in average condition at time of purchase

MMRAcquisitionAuctionCleanPrice		Acquisition price for this vehicle in the above Average condition at time of purchase

MMRAcquisitionRetailAveragePrice	Acquisition price for this vehicle in the retail market in average condition at time of purchase

MMRAcquisitonRetailCleanPrice		Acquisition price for this vehicle in the retail market in above average condition at time of purchase

MMRCurrentAuctionAveragePrice		Acquisition price for this vehicle in average condition as of current day

MMRCurrentAuctionCleanPrice		Acquisition price for this vehicle in the above condition as of current day

MMRCurrentRetailAveragePrice		Acquisition price for this vehicle in the retail market in average condition as of current day

MMRCurrentRetailCleanPrice		Acquisition price for this vehicle in the retail market in above average condition as of current day

PRIMEUNIT				Identifies if the vehicle would have a higher demand than a standard purchase

AcquisitionType				Identifies how the vehicle was aquired (Auction buy, trade in, etc)

AUCGUART				The level guarntee provided by auction for the vehicle (Green light - Guaranteed/arbitratable, Yellow Light - caution/issue, red light - sold as is)

KickDate				Date the vehicle was kicked back to the auction

BYRNO					Unique number assigned to the buyer that purchased the vehicle

VNZIP                                   Zipcode where the car was purchased

VNST                                    State where the the car was purchased

VehBCost				Acquisition cost paid for the vehicle at time of purchase

IsOnlineSale				Identifies if the vehicle was originally purchased online

WarrantyCost                            Warranty price (term=36month  and millage=36K)

## Расмотрим задачу по другому
Я не особо доволен результатами. Так как точность и полнота на классах 1 очень маленькая. Может дело в признаках?
Сравним два элемента разного класса. Может упушенны важные признаки? В ценах у них небольшая разница. Большая разница в стоимости покупки(VehBCost) и в страховке(WarrantyCost). Попробуем учесть эти факторы

In [40]:
from IPython.display import display
pd.options.display.max_columns = None
display(data.loc[data['IsBadBuy']==1][3:4],data.loc[data['IsBadBuy']==0][3:4])

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
35,36,1,12/28/2009,ADESA,2001,8,FORD,WINDSTAR FWD V6,LX,PASSENGER 3.8L LX,GOLD,AUTO,1.0,Alloy,82944,AMERICAN,VAN,FORD,1805.0,2423.0,4318.0,5562.0,1840.0,2640.0,4407.0,5530.0,NaN,NaN,19638,33619,FL,3600.0,0,2322

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,WheelType,VehOdo,Nationality,Size,TopThreeAmericanName,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
3,4,0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,Alloy,65617,AMERICAN,COMPACT,CHRYSLER,1893.0,2675.0,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630

## 2 Обработка данных

In [41]:
import sklearn
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
car_data=data[['IsBadBuy','VehicleAge','VehOdo','MMRAcquisitionAuctionAveragePrice',
               'MMRCurrentAuctionAveragePrice','MMRAcquisitionAuctionCleanPrice','MMRAcquisitionRetailAveragePrice',
               'MMRAcquisitonRetailCleanPrice','MMRCurrentAuctionCleanPrice','MMRCurrentRetailAveragePrice',
               'MMRCurrentRetailCleanPrice','WarrantyCost','VehBCost']]
car_data=car_data.dropna()


car_data['MMRAcquisitionAuctionAveragePrice']=car_data['MMRAcquisitionAuctionAveragePrice']*10/car_data['VehBCost']
car_data['MMRCurrentAuctionAveragePrice']=car_data['MMRCurrentAuctionAveragePrice']*10/car_data['VehBCost']
car_data['MMRAcquisitionAuctionCleanPrice']=car_data['MMRAcquisitionAuctionCleanPrice']*10/car_data['VehBCost']
car_data['MMRAcquisitionRetailAveragePrice']=car_data['MMRAcquisitionRetailAveragePrice']*10/car_data['VehBCost']
car_data['MMRAcquisitonRetailCleanPrice']=car_data['MMRAcquisitonRetailCleanPrice']*10/car_data['VehBCost']
car_data['MMRCurrentAuctionCleanPrice']=car_data['MMRCurrentAuctionCleanPrice']*10/car_data['VehBCost']
car_data['MMRCurrentRetailAveragePrice']=car_data['MMRCurrentRetailAveragePrice']*10/car_data['VehBCost']
car_data['MMRCurrentRetailCleanPrice']=car_data['MMRCurrentRetailCleanPrice']*10/car_data['VehBCost']

y=car_data[['IsBadBuy']]
car_data=car_data.drop(['IsBadBuy','VehBCost'],axis=1)
X=car_data.to_numpy()
y=y.to_numpy()
x_train, x_test, y_train, y_test = train_test_split(X, y,train_size=0.95,random_state=42)
car_data

,VehicleAge,VehOdo,MMRAcquisitionAuctionAveragePrice,MMRCurrentAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,WarrantyCost
0,3,89046,11.485915,10.494366,13.843662,16.388732,19.154930,12.045070,16.333803,17.477465,1113
1,5,93593,9.018421,9.810526,11.030263,14.338158,16.542105,12.134211,14.965789,16.830263,1053
2,4,73807,6.534694,8.234694,9.714286,14.169388,17.259184,11.340816,14.583673,17.759184,1389
3,5,65617,4.617073,4.497561,6.524390,11.360976,13.878049,6.453659,10.670732,13.458537,630
4,4,69367,9.782500,8.117500,12.635000,19.307500,21.767500,10.960000,16.847500,19.777500,1020
...,...,...,...,...,...,...,...,...,...,...,...
72978,8,45234,4.752381,5.214286,7.126190,6.323810,8.885714,7.273810,11.514286,14.135714,993
72979,2,71759,10.351613,10.943548,11.814516,11.985484,13.566129,13.116129,16.372581,18.793548,1038
72980,4,88500,10.420732,10.213415,12.145122,11.864634,13.726829,11.953659,14.428049,17.563415,1893
72981,3,79554,9.171429,9.414286,10.862857,10.620000,12.445714,10.977143,14.427143,16.040000,1974
72982,3,66855,9.418750,9.662500,10.963750,10.797500,12.466250,11.377500,14.942500,16.557500,1313

## 3 Работа с моделью

In [42]:

from sklearn import *
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings; warnings.simplefilter('ignore')
model = RandomForestClassifier(n_estimators=150, max_depth=20)
model.fit(x_train, y_train)
pred=model.predict(x_test)
print("forest: ",metrics.classification_report(y_test, pred))
tree = DecisionTreeClassifier(max_depth=20)
tree.fit(x_train, y_train)
tree_pred=tree.predict(x_test)
print("tree: ",metrics.classification_report(y_test, tree_pred))

forest:                precision    recall  f1-score   support

           0       0.87      1.00      0.93      3160
           1       0.50      0.02      0.04       474

    accuracy                           0.87      3634
   macro avg       0.69      0.51      0.49      3634
weighted avg       0.82      0.87      0.81      3634

tree:                precision    recall  f1-score   support

           0       0.88      0.93      0.90      3160
           1       0.22      0.14      0.17       474

    accuracy                           0.82      3634
   macro avg       0.55      0.53      0.54      3634
weighted avg       0.79      0.82      0.81      3634